### ISSUE TITLE
Right order to create translations

### ISSUE THREAD

**Issue by brunovila** [zostera/django-modeltrans#39] opened 2018-04-02 23:28 UTC
In order to add translations to a field in a Model, If I create the Model class, make the migrations to DB and then I add the i18n field, it works OK

but

If I create the model class with the i18n field directly it fails when I apply the migrations.

**Comment by dyve** [comment] 2018-04-03 04:41
I think this is a duplicate of #36

**Comment by jieter** [comment] 2018-04-13 12:41
yes, this is.

**Closed as completed by jieter** 2018-04-13 12:41 UTC
